### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by jeromim** [x0rnn/minqlx-plugins#1]
Autospec: Picked adq^4|^7NaraK^7 from the red team.
[minqlx.killingspree.log_exception] ERROR: Traceback (most recent call last):
[minqlx.killingspree.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.killingspree.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.killingspree.log_exception] ERROR: TypeError: handle_round_countdown() takes 1 positional argument but 2 were given
Client 7 connecting with 50 challenge ping

**Comment by x0rnn** [comment]
Fixed.
