### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jeromim** [x0rnn/minqlx-plugins#2]
(16:33:03) [DEBUG @ minqlx.dispatch] map('solid', 'ca')
(16:33:03) [DEBUG @ minqlx.dispatch] new_game()
(16:33:09) [DEBUG @ minqlx.dispatch] player_spawn(Player(11:'Glare':76561197991305108),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_loaded(Player(11:'Glare':76561197991305108),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_spawn(Player(3:'amaru':76561197989971812),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_loaded(Player(3:'amaru':76561197989971812),)
(16:33:09) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'userinfo "\ip\187.65.144.145:27960\ui_singl)
(16:33:09) [DEBUG @ minqlx.dispatch] player_spawn(Player(2:'bd Qixâ™•':76561198017151203),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_loaded(Player(2:'bd Qixâ™•':76561198017151203),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_spawn(Player(8:'Warumnicht':76561198205626664),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_loaded(Player(8:'Warumnicht':76561198205626664),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_spawn(Player(12:'pedreiro':76561198029829058),)
(16:33:09) [DEBUG @ minqlx.dispatch] player_loaded(Player(12:'pedreiro':76561198029829058),)
(16:33:10) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'score')
(16:33:10) [DEBUG @ minqlx.dispatch] player_spawn(Player(9:'bd | cobalt':76561198176861786),)
(16:33:10) [DEBUG @ minqlx.dispatch] player_loaded(Player(9:'bd | cobalt':76561198176861786),)
(16:33:13) [DEBUG @ minqlx.dispatch] client_command(Player(2:'bd Qixâ™•':76561198017151203), 'callvote map almostlost ')
(16:33:13) [DEBUG @ minqlx.dispatch] vote_called(Player(2:'bd Qixâ™•':76561198017151203), 'map', 'almostlost ')
(16:33:13) [DEBUG @ minqlx.handle_console_print] broadcast: print "^4bd ^7Qixâ™• called a vote.\n"
(16:33:13) [DEBUG @ minqlx.dispatch] vote_started(Player(2:'bd Qixâ™•':76561198017151203), 'map', 'almostlost')
(16:33:15) [DEBUG @ minqlx.dispatch] player_spawn(Player(4:'fkr':76561198121509868),)
(16:33:15) [DEBUG @ minqlx.dispatch] player_loaded(Player(4:'fkr':76561198121509868),)
(16:33:15) [DEBUG @ minqlx.dispatch] client_command(Player(4:'fkr':76561198121509868), 'userinfo "\ip\187.180.179.72:2740\ui_singlePl)
(16:33:16) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'vote no')
(16:33:16) [DEBUG @ minqlx.dispatch] vote(Player(3:'amaru':76561197989971812), False)
(16:33:19) [DEBUG @ minqlx.dispatch] player_spawn(Player(8:'Warumnicht':76561198205626664),)
(16:33:23) [DEBUG @ minqlx.dispatch] player_spawn(Player(11:'Glare':76561197991305108),)
(16:33:29) [DEBUG @ minqlx.dispatch] client_command(Player(9:'bd | cobalt':76561198176861786), 'score')
(16:33:31) [DEBUG @ minqlx.dispatch] player_spawn(Player(11:'Glare':76561197991305108),)
(16:33:33) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'score')
(16:33:34) [DEBUG @ minqlx.dispatch] client_command(Player(8:'Warumnicht':76561198205626664), 'vote yes')
(16:33:34) [DEBUG @ minqlx.dispatch] vote(Player(8:'Warumnicht':76561198205626664), True)
(16:33:34) [DEBUG @ minqlx.dispatch] player_spawn(Player(8:'Warumnicht':76561198205626664),)
(16:33:35) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'score')
(16:33:36) [DEBUG @ minqlx.dispatch] player_spawn(Player(9:'bd | cobalt':76561198176861786),)
(16:33:36) [DEBUG @ minqlx.dispatch] client_command(Player(2:'bd Qixâ™•':76561198017151203), 'score')
(16:33:37) [DEBUG @ minqlx.dispatch] client_command(Player(9:'bd | cobalt':76561198176861786), 'score')
(16:33:37) [DEBUG @ minqlx.dispatch] player_spawn(Player(2:'bd Qixâ™•':76561198017151203),)
(16:33:41) [DEBUG @ minqlx.handle_console_print] broadcast: print "^1New map record^7! ^4bd ^7Qixâ™• killed Glare from a distance of: ^1409 ^7units. Score: ^21^7:^20\n"\n\n
(16:33:42) [DEBUG @ minqlx.dispatch] vote_ended((2, 1), 'map', 'almostlost', True)
(16:33:42) [DEBUG @ minqlx.handle_console_print] broadcast: print "Vote passed.\n"
(16:33:42) [DEBUG @ minqlx.handle_console_print] broadcast: print "Vote results: ^22^7 - ^11^7.\n"\n\n
(16:33:42) [DEBUG @ minqlx.handle_console_print] broadcast: print "The map is changing to ^4almostlost^7.\n"\n\n
(16:33:43) [DEBUG @ minqlx.dispatch] player_spawn(Player(11:'Glare':76561197991305108),)
(16:33:43) [DEBUG @ minqlx.dispatch] client_command(Player(4:'fkr':76561198121509868), 'score')
(16:33:44) [DEBUG @ minqlx.dispatch] client_command(Player(9:'bd | cobalt':76561198176861786), 'readyup')
(16:33:44) [DEBUG @ minqlx.dispatch] client_command(Player(3:'amaru':76561197989971812), 'score')
(16:33:44) [DEBUG @ minqlx.dispatch] client_command(Player(9:'bd | cobalt':76561198176861786), 'score')
(16:33:45) [DEBUG @ minqlx.dispatch] client_command(Player(11:'Glare':76561197991305108), 'score')
(16:33:45) [DEBUG @ minqlx.dispatch] player_spawn(Player(4:'fkr':76561198121509868),)
(16:33:45) [DEBUG @ minqlx.handle_console_print] ==== ShutdownGame ====
(16:33:45) [DEBUG @ minqlx.handle_console_print] AAS shutdown.
(16:33:45) [DEBUG @ minqlx.handle_console_print] ------ Server Initialization ------
(16:33:45) [DEBUG @ minqlx.handle_console_print] Server: almostlost
(16:33:45) [DEBUG @ minqlx.handle_console_print] Hunk_Clear: reset the hunk ok
(16:33:45) [DEBUG @ minqlx.handle_console_print] ----- FS_Startup -----
(16:33:45) [DEBUG @ minqlx.handle_console_print] Current search path:
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/.quakelive/27960/baseq3
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/baseq3/pak00.pk3 (0x15a37833 - 9285 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/baseq3/bin.pk3 (0x7c1d0d5e - 5 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/baseq3
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/qzeroded.x64/baseq3
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/701783942//killingspree.pk3 (0xca1c14ec - 15 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/701783942/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/691078677//workshop_gibs.pk3 (0xb0ecd557 - 32 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/691078677/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/607068129//uberkill.pk3 (0x81823143 - 22 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/607068129/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/606599547//heroscerated.pk3 (0x094a3540 - 13 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/606599547/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/605561819//OverkillPP.pk3 (0x39353f15 - 37 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/605561819/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/572015381//ql_dust2.pk3 (0x90540cc8 - 35 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/572015381//ql_dust.pk3 (0xf0378cb9 - 68 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/572015381/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/562042961//ra3map17.pk3 (0x8fd1c685 - 110 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/562042961/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561877295//ra3map7.pk3 (0xd2322b9b - 77 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561877295/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561815150//ra3map4.pk3 (0x9922c86d - 44 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561815150/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561459991//ra3map5.pk3 (0x4c4a77d4 - 40 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561459991/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561613916//ra3map3.pk3 (0x87d869e0 - 57 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/561613916/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560547573//NAL.pk3 (0x0da6b911 - 19 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560547573/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560545593//dm102.pk3 (0xfad48607 - 133 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560545593/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560647562//dm6remix.pk3 (0x04678cd0 - 9 files)
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/560647562/
(16:33:45) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/553095317//ra3map6.pk3 (0x830e2cf0 - 93 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/553095317/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/553088484//ra3map22.pk3 (0x0ad5a6a1 - 361 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/553088484/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/551699225//ra3map21.pk3 (0x7a3f48f7 - 33 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/551699225/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/551229107//ra3map20.pk3 (0xfcb5b0f3 - 219 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/551229107/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550003921//ra3map18.pk3 (0x2dece0dd - 43 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550003921/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550843679//ra3map10.pk3 (0x4d5b2c2d - 168 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550843679/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550674410//ra3map13.pk3 (0xebc46f3b - 74 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550674410/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550575965//ra3map15.pk3 (0x446471aa - 181 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550575965/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550566693//ra3map16.pk3 (0x7435ad07 - 122 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/550566693/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549600167//okremix.pk3 (0x70df4822 - 7 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549600167/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549447613//ra3map14.pk3 (0x77dd8bbb - 17 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549447613/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549208258//ra3map19.pk3 (0x9f09854b - 54 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/549208258/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/539421982//workshop_holiday.pk3 (0x2066bc07 - 56 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/539421982/
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/539421606//workshop_extras.pk3 (0x47805cc3 - 261 files)
(16:33:46) [DEBUG @ minqlx.handle_console_print] /home/ubuntu/steamcmd/steamapps/common/qlca/steamapps/workshop/content/282440/539421606/
(16:33:46) [DEBUG @ minqlx.handle_console_print](16:33:46) [DEBUG @ minqlx.handle_console_print] ----------------------
(16:33:46) [DEBUG @ minqlx.handle_console_print] 11690 files in pk3 files
(16:33:46) [DEBUG @ minqlx.handle_console_print] Loading dll file qagame
(16:33:46) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) found **dllEntry** at  0x7f573459f180  
(16:33:46) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) succeeded!
(16:33:46) [DEBUG @ minqlx.handle_console_print] Sys_SetModuleOffset: qagame 0x7F573459F180
(16:33:46) [DEBUG @ minqlx.handle_console_print] ------- Game Initialization -------
(16:33:46) [DEBUG @ minqlx.handle_console_print] gamename: baseqz
(16:33:46) [DEBUG @ minqlx.handle_console_print] gamedate: May 25 2016
(16:33:46) [DEBUG @ minqlx.handle_console_print] initializing access list...
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded 7 steam ids into the access list
(16:33:46) [DEBUG @ minqlx.handle_console_print] Not logging to disk.
(16:33:46) [DEBUG @ minqlx.handle_console_print] 0 teams with 0 entities
(16:33:46) [DEBUG @ minqlx.handle_console_print] 0 items registered
(16:33:46) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(16:33:46) [DEBUG @ minqlx.handle_console_print] ------- BotLib Initialization -------
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded weapons.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded items.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded syn.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded rnd.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded match.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded rchat.c
(16:33:46) [DEBUG @ minqlx.handle_console_print] ------------ Map Loading ------------
(16:33:46) [DEBUG @ minqlx.handle_console_print] trying to load maps/almostlost.aas
(16:33:46) [DEBUG @ minqlx.handle_console_print] loaded maps/almostlost.aas
(16:33:46) [DEBUG @ minqlx.handle_console_print] found 44 level items
(16:33:46) [DEBUG @ minqlx.handle_console_print] -------------------------------------
(16:33:46) [DEBUG @ minqlx.handle_console_print] 34 bots parsed
(16:33:46) [DEBUG @ minqlx.handle_console_print] AAS initialized.
(16:33:46) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(16:33:46) [DEBUG @ minqlx.dispatch] map('almostlost', 'ca')
(16:33:46) [DEBUG @ minqlx.dispatch] new_game()
(16:33:47) [DEBUG @ minqlx.handle_console_print] qagame: 0x7F573459F180
 cgame: 0x0
    ui: 0x0
[0x4526B6]
[0x7F573F87F340]
[0x7F573EAC3A03]
[0x7F573EB81235]
[0x7F57345A017C]
[0x7F5734582106]
[0x7F573458D7C5]
[0x43AB60]
[0x4250CC]
[0x42522D]
[0x450BB9]
[0x4078EE]
[0x7F573EA99EC5]
[0x4079F9](16:33:47) [DEBUG @ minqlx.handle_console_print] version: 1069 linux-x64 Jun  3 2016 20:53:50
(16:33:47) [DEBUG @ minqlx.handle_console_print] g_version: 1069 linux-x64 May 25 2016 20:02:46
(16:33:47) [DEBUG @ minqlx.handle_console_print] ----- Server Shutdown -----
(16:33:47) [DEBUG @ minqlx.handle_console_print] ==== ShutdownGame ====
(16:33:47) [DEBUG @ minqlx.handle_console_print] AAS shutdown.
(16:33:47) [DEBUG @ minqlx.handle_console_print] ---------------------------
(16:33:54) [INFO @ minqlx._configure_logger] ============================= minqlx run @ 2016-06-19 16:33:54.134058 =============================
(16:33:54) [INFO @ minqlx.late_init] Loading preset plugins...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'killingspree'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'queue'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'motd'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'aliases'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'autospec'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'permission'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'patch'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'names'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'player_info'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'checkplayers'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'commlink'...
(16:33:54) [INFO @ minqlx.commlink.__init__] Connecting to irc.tomtecsolutions.com.au...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'branding'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'pummel'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'midair'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'workshop'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'essentials'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'centerprint'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'votemanager'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'log'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'servers'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'silence'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'clanmembers'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'balance'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'votestats'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'info'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'plugin_manager'...
(16:33:54) [INFO @ minqlx.load_plugin] Loading plugin 'ban'...
(16:33:54) [INFO @ minqlx.late_init] Stats listener started on tcp://127.0.0.1:27960.
(16:33:54) [INFO @ minqlx.late_init] We're good to go!
(16:33:54) [DEBUG @ minqlx.dispatch] map('campgrounds', 'ca')

**Comment by x0rnn** [comment]
I don't see anything crashing.

**Comment by jeromim** [comment]
ok :)
